### ISSUE TITLE
No Molex 5566-3 connector

### ISSUE THREAD

**Issue by mnelson920** [chiengineer/Eagle-Libraries#5]
Hi,

Will there by a Molex 5566-3 connector added to this library?

Thanks,
Mark

**Comment by JensGrabner** [comment]
Have you a Molex Part Number about this Product ?

**Comment by mnelson920** [comment]
@JensGrabner, yes its is: Part Number: 39-30-1039

**Comment by JensGrabner** [comment]
I found 2 technical Dawings about that.
http://www.farnell.com/cad/469271.pdf
http://www.molex.com/pdm_docs/sd/039301039_sd.pdf
You must make self  ...  the Library.

**Comment by mnelson920** [comment]
Ok thanks
